#!/usr/bin/env bash

main() {
    local compose_dir="compose"
    local dockerfile_dir="dockerfiles"

    local docker_compose_file="${compose_dir}/docker-compose.yml"
    local docker_compose_override_file="${compose_dir}/docker-compose-override.stack.yml"
    local docker_stack_file="${compose_dir}/docker-stack.yml"
    local api_base_dockerfile="${dockerfile_dir}/manifold_api_base/Dockerfile"
    local api_cable_dockerfile="${dockerfile_dir}/manifold_api_cable/Dockerfile"
    local api_clockwork_dockerfile="${dockerfile_dir}/manifold_api_clockwork/Dockerfile"
    local api_rails_dockerfile="${dockerfile_dir}/manifold_api_rails/Dockerfile"
    local api_sidekiq_dockerfile="${dockerfile_dir}/manifold_api_sidekiq/Dockerfile"
    local client_dockerfile="${dockerfile_dir}/manifold_client/Dockerfile"
    local proxy_dockerfile="${dockerfile_dir}/manifold_proxy/Dockerfile"

    local manifold_src="${HOME}/src/manifold"
    local lib_dir="lib/manifold-docker"

    if [ ! -f "${docker_compose_file}" ]
    then
        error_message "Can't locate: $(pwd)/compose/docker-compose.yml"
        error_message "Please run from the root of manifold docker project."
        help_message
        exit 1
    fi

    local lib_files=$(ls -ap ${lib_dir} | grep -v "\./" | grep -v "\../")

    if [[ ${lib_files[*]} == '' ]]
      then
        error_message "Unable to load command files from: ${lib_dir}"
      else
        for lib_file in ${lib_files[@]}; do
          source "${lib_dir}/${lib_file}"
        done
      fi

    case "${1}" in
        build)
            shift
            build manifold_version="${1}" manifold_image="${2}"
            ;;
        compose)
            shift
            _create_docker_machine
            compose "$@"
            ;;
        stack)
            shift
            _create_docker_machine
            stack "$@"
            ;;
        *)
            help_message
    esac
}

help_message() {

    local base_usage=$0
    local base_commands=("build" "compose" "stack")

    local usage_example=${base_usage}


    if [[ -n ${1} ]]
    then
        usage_example="${base_usage} ${1}"
    fi

    if [[ -n ${2} ]]
    then
        unset base_commands
        commands="${2}"
    fi

cat <<HelpMessage

Usage: ${usage_example}

Commands:

    `printf '\t%s\n' "${base_commands[@]}"`
    `printf '\t%s\n' "${commands[@]}"`


HelpMessage

}

error_message() {
    printf "\n[!] %s [!]\n" "${1}"
}

standard_message() {
    printf "\n%s\n" "${1}"
}

main $*