ARG MANIFOLD_VERSION

FROM manifoldscholar/manifold_api_base:$MANIFOLD_VERSION

COPY dockerfiles/manifold_api_clockwork/scripts/start-and-run /opt/manifold/api/start-and-run

WORKDIR /opt/manifold/api
