#!/usr/bin/env bash

stack() {
    case "${1}" in
        up)
            if [[ -z ${2} ]]
            then
                local commands=("VERSION (x.x.x)")
                error_message "You must specify the version of Manifold."
                help_message "${FUNCNAME[0]} ${1}" "${commands[@]}"
                exit 1
            fi
            MANIFOLD_DOMAIN=${3}
            _stack_up manifold_tag=${2}
            ;;
        down)
            _stack_down
            ;;
        run)
            if [[ -z ${2} ]]
            then
                local commands=("SERVICE")
                error_message "You must specify the service you wish to run the command on."
                help_message "${FUNCNAME[0]} ${1}" "${commands[@]}"
                exit 1
            fi
            _stack_run service="${2}" prompt=1
            ;;
        *)
            local commands=("up" "down" "run")
            help_message ${FUNCNAME[0]} "${commands[@]}"
    esac

}

_stack_up() {
    local manifold_tag
    local "${@}"
    export MANIFOLD_TAG=${manifold_tag} DOCKER_IP=$(_get_docker_ip) DOCKER_IP_OR_DOMAIN=$(_get_docker_ip_or_domain)
    _stack_generate_config
    docker swarm init --advertise-addr $(_get_docker_ip)
    docker-compose -f ${docker_stack_file} pull
    docker stack deploy -c ${docker_stack_file} manifold
    __manifold_api_loading
    __postgres_loading swarm_mode=1
    _stack_run service="manifold_api" command="cd api && bin/rails db:migrate" prompt=0
    _stack_run service="manifold_api" command="cd api && bin/rails db:seed" prompt=0
    _stack_run service="manifold_api" \
    command="cd api && rails manifold:user:create:admin['email@example.com','M@n1f0ld','First','Last']" prompt=0
    __manifold_client_loading swarm_mode=1
    _stack_help_message
}

_stack_down(){
    docker stack rm manifold
    docker swarm leave --force
}

_stack_run() {
    local service command prompt
    local "${@}"
     if [ ${prompt} == 1 ]
    then
        standard_message "Service set to [${service}]. What command would you like to run?"
        read command
    fi
    standard_message "Service set to [${service}]. Attempting to run: ${command}"
    docker exec ${service}.1.$(docker service ps -f "name=${service}.1" ${service} -q) /bin/bash -c "${command}"
}

_stack_generate_config() {
    docker-compose -f ${docker_compose_file} -f ${docker_compose_override_file} config > ${docker_stack_file}
}
_stack_help_message() {
cat <<StackHelpMessage

    Manifold:
        https://$(_get_docker_ip_or_domain):4000/

    Admin User: email@example.com
    Admin Password: M@n1f0ld

    Setup additional admin user:
        eval \$(docker-machine env manifold1) # Required if running on macOS
        docker exec -it compose_api_1 /bin/bash -c "cd api && rails manifold:user:create:admin['email@example.com','M@n1f0ld','First','Last']"

    Visualizer:
        http://$(_get_docker_ip_or_domain):8084
    Example API route:
        https://$(_get_docker_ip_or_domain):4000/api/v1/projects

    Teardown command:
        ./manifold-docker stack down
StackHelpMessage
}