#!/usr/bin/env bash
# start-and-run [...]
set -e

CMD="$@"

# Wait for PostgreSQL
until psql -h ${RAILS_DB_HOST} -U ${RAILS_DB_USER} -c '\q'; do
  >&2 echo "Postgres is unavailable - sleeping"
  sleep 1
done

>&2 echo "Postgres is up - executing command"

# Setup PostgreSQL Database
bin/rails db:migrate && bin/rails db:seed && \
bin/rails manifold:user:create:admin['email@example.com','M@n1f0ld','First','Last']

# Run additional command(s) added to docker-compose.yml
exec ${CMD}
